[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["openai"]

# Make /api/* hit your functions
[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat_v2"
  status = 200
  force  = true

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

  [[redirects]]
  from = "/api/events"
  to   = "/.netlify/functions/events-get"
  status = 200
  force  = true


[[headers]]
  for = "/index.html"
  [headers.values]
  Cache-Control = "no-cache, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
  # Let pages default to revalidation; functions add their own headers.
  Cache-Control = "no-cache, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
  # Let Vite’s hashed assets be cached long-term
  Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  NODE_VERSION = "20"
