# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

# ONE global functions block (only once)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Per-function overrides go in named tables (this is where region goes)
[functions."chat_v2"]
  regions = ["us-east-1"]   # pick what's closest to you/users

# Scheduled function pings the chat lambda every 5 mins to keep it warm
[[scheduled]]
  path = "/.netlify/functions/warm"
  schedule = "*/5 * * * *"

# Your existing redirects (example)
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat_v2"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
