# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."chat_v2"]
  regions = ["us-east-1"]  # choose the closest region to your users

[[scheduled]]
  path = "/.netlify/functions/warm"
  schedule = "*/5 * * * *"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat_v2"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
